package lt.biblioteka.biblioteka.mybatis.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.NAME
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.LIBRARY_ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    private Long libraryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.READER_ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    private Long readerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ID
     *
     * @return the value of PUBLIC.BOOK.ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ID
     *
     * @param id the value for PUBLIC.BOOK.ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.NAME
     *
     * @return the value of PUBLIC.BOOK.NAME
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.NAME
     *
     * @param name the value for PUBLIC.BOOK.NAME
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.LIBRARY_ID
     *
     * @return the value of PUBLIC.BOOK.LIBRARY_ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public Long getLibraryId() {
        return libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.LIBRARY_ID
     *
     * @param libraryId the value for PUBLIC.BOOK.LIBRARY_ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public void setLibraryId(Long libraryId) {
        this.libraryId = libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.READER_ID
     *
     * @return the value of PUBLIC.BOOK.READER_ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public Long getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.READER_ID
     *
     * @param readerId the value for PUBLIC.BOOK.READER_ID
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    public void setReaderId(Long readerId) {
        this.readerId = readerId;
    }
}