package lt.biblioteka.biblioteka.mybatis.dao;

import java.util.List;
import lt.biblioteka.biblioteka.mybatis.model.Book;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    List<Book> selectAll();

    List<Book> loadLibraryBooks(Long libraryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int updateByPrimaryKey(Book record);
}