package lt.biblioteka.biblioteka.mybatis.dao;

import java.util.List;
import lt.biblioteka.biblioteka.mybatis.model.Library;

public interface LibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int insert(Library record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    Library selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    List<Library> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LIBRARY
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int updateByPrimaryKey(Library record);
}