package lt.biblioteka.biblioteka.mybatis.dao;

import java.util.List;
import lt.biblioteka.biblioteka.mybatis.model.Reader;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.READER
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.READER
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.READER
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    Reader selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.READER
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    List<Reader> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.READER
     *
     * @mbg.generated Fri Mar 21 16:59:41 EET 2025
     */
    int updateByPrimaryKey(Reader record);


}